### ISSUE TITLE
please, don't link html in inetnums!

### ISSUE THREAD

**Issue by massimocandela** [Gnetwork-networkteam/GeoLocation_RIPE#2]
hey,

In whois you are linking  https://github.com/Gnetwork-networkteam/GeoLocation_RIPE/blob/main/Geoloc.csv which is an HTML page, instead of

https://raw.githubusercontent.com/Gnetwork-networkteam/GeoLocation_RIPE/main/Geoloc.csv which is the correct CSV file.

```
inetnum:        185.226.37.0 - 185.226.37.255
netname:        UK-GNETWORK-54
country:        GB
admin-c:        SV6636-RIPE
tech-c:         SN6433-RIPE
status:         ASSIGNED PA
mnt-by:         uk-gnetwork-1-mnt
created:        2020-04-29T14:05:21Z
last-modified:  2022-07-19T13:14:36Z
source:         RIPE
geofeed:        https://github.com/Gnetwork-networkteam/GeoLocation_RIPE/blob/main/Geoloc.csv
```

This makes your geofeed efforts vain, since the result is not RFC8805 parsable. Please, fix it! Thanks.

**Comment by A-Graham-G-Network** [comment]
All updated and thanks for the heads-up.
